---
version: 2

templates:
  cache: &cache
    key: v1-{{ checksum "setup.py" }}-{{ checksum "circle.yml" }}

jobs:

  test:
    working_directory: ~/whats-on-microservice
    docker:
      - image: circleci/python:3.6
    environment:
      CC_REPORTER: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    steps:
      - checkout
      - restore_cache:
          <<: *cache
      - run:
          name: Install Requirements
          command: |
            if [[ ! -d ~/.venv ]]; then
              python -m venv ~/.venv
              . ~/.venv/bin/activate
              pip install -e .
              python setup.py test_requirements
              curl -L "$CC_REPORTER" > ~/.venv/bin/cc-test-reporter
              chmod +x ~/.venv/bin/cc-test-reporter
            fi
      - run:
          name: Test
          command: |
            . ~/.venv/bin/activate
            export TABLE_METADATA=whats-on-table-metadata-demo
            export TABLE_SUBSCRIBERS=whats-on-table-subscribers-demo
            cc-test-reporter before-build
            pytest \
              --junitxml=test-results/pytest/results.xml \
              --cov-report=xml:coverage.xml
            cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?
            # run integration tests
            for func_test in functests/*.py ; do python $func_test ; done
      - save_cache:
          <<: *cache
          paths:
            - ~/.venv
            - ~/whats-on-microservice/.eggs
            - ~/whats-on-microservice/whats_on_microservice.egg-info
      - store_test_results:
          path: ~/whats-on-microservice/test-results/


  build_lambda:
    working_directory: ~/whats-on-microservice
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Build Lambda
          command: |
            mkdir -p workspace/pkg
            pip install -U git+https://github.com/nypublicradio/nyprsetuptools.git --user
            pip install . -t workspace/pkg
      - persist_to_workspace:
          root: workspace
          paths:
            - pkg


  deploy_lambda:
    working_directory: ~/whats-on-microservice
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - restore_cache:
          <<: *cache
      - run:
          name: Deploy Lambda
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]] || [[ "${CIRCLE_TAG}" == "demo" ]]; then
              export ENV=demo
              export TAG=demo
              export DEMO_RELEASE=$CIRCLE_SHA1
            elif echo "$CIRCLE_TAG" | grep -q "v[0-9]\+\.[0-9]\+\.[0-9]\+"; then
              export ENV=prod
              export TAG=$CIRCLE_TAG
              export PROD_RELEASE=$TAG
            else
              exit 1
            fi
            . ~/.venv/bin/activate
            python setup.py deploy \
              --environment=$ENV \
              --function-name=whats-on \
              --function-handler=whatsonms.handler \
              --package-dir=workspace/pkg \
              --no-s3


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build_lambda:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy_lambda:
          requires:
            - build_lambda
          filters:
            tags:
              only: 
                - /^v[0-9]+\.[0-9]+\.[0-9]+/
                - demo
            branches:
              only: master


experimental:
  notify:
    branches:
      only:
        - master
